// <auto-generated />
using System;
using CinemaProjectASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaProjectASP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaProjectASP.Models.Aktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Biografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImieNazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RokUrodzenia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Aktors");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Aktor_Film", b =>
                {
                    b.Property<int>("AktorId")
                        .HasColumnType("int");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.HasKey("AktorId", "FilmId");

                    b.HasIndex("FilmId");

                    b.ToTable("Aktors_Films");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<DateTime>("DoKiedy")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmKategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OdKiey")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RezyserId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RezyserId");

                    b.HasIndex("SalaId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Rezyser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Biografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImieNazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RokUrodzenia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rezysers");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Aktor_Film", b =>
                {
                    b.HasOne("CinemaProjectASP.Models.Aktor", "Aktor")
                        .WithMany("Aktors_Films")
                        .HasForeignKey("AktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProjectASP.Models.Film", "Film")
                        .WithMany("Aktors_Films")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktor");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Film", b =>
                {
                    b.HasOne("CinemaProjectASP.Models.Rezyser", "Rezyser")
                        .WithMany("Films")
                        .HasForeignKey("RezyserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProjectASP.Models.Sala", "Sala")
                        .WithMany("Films")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezyser");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Aktor", b =>
                {
                    b.Navigation("Aktors_Films");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Film", b =>
                {
                    b.Navigation("Aktors_Films");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Rezyser", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("CinemaProjectASP.Models.Sala", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
